---
title: "ST558 Project 1: Group A"
author: "Eric Song & Jay Thakur"
format: html
editor: visual
---

*Loading required libraries, include = FALSE.*

```{r, include=FALSE}
library(tidyverse)
library(httr)
library(tidycensus)
library(jsonlite)
```

# API Call

### TODO: 
Data processing: 
Data cleaning:
Subsetting data.
Will add narrative on sunday.  

```{r}
Pums_APIdata <- function(year=2022, num_variables =c("AGEP","PWGTP"),cat_variables="SEX",geography="ALL",Opt_subset){
   #Year Range Check
  if (year < 2010 | year > 2022){
    print("Invalid Year.  Acceptable year range: 2010-2022.")
    return()
    }
  #TODO: add error checking for numeric/categorical/geography
  
  
  #API key here:
  API_key<-"2b989c8e8efa3003c17e6eb0ca728a968e04a441" 
  #Automatically capitalize our variables
  num_variables<-toupper(num_variables)
  cat_variables<-toupper(cat_variables)
  geography<-toupper(geography)
  #Adding num/cat variables to our url
  variables_url<-paste(c(num_variables,cat_variables),collapse=",")
  #Base URL w/ year variable
  base_pums_url <-paste("https://api.census.gov/data/",year,"/acs/acs1/pums?get=",variables_url,sep="")
  #Adding geography to URL
  if (geography == "ALL"){
    geo_url <- paste(base_pums_url,"&SCHL=24&key=",API_key,sep="")}
    else if (geography == "REGION"){
      geo_url <- paste(base_pums_url,"&for=region:*&SCHL=24&key=",API_key,sep="")}
    else if (geograph == "DIVISION"){
      geo_url <- paste(base_pums_url,"for=division:*&SCHL=24&key=",API_key,sep="")}
    else if (geography == "STATE"){
      geo_url <- paste(base_pums_url,"&for=state:*&SCHL=24&key=",API_key,sep="")}
  
  #API Fetch:
  pums_fetch <- httr::GET(geo_url)
  #Decoding data
  pums_df <- fromJSON(rawToChar(pums_fetch$content))
  pums_tibble <-as_tibble(pums_df)
  
  #TODO: Clean data.  Fix column names etc...
  #TODO: Subset data for geography
  
  
  #change return to cleaned dataframe.
  return(pums_tibble)
  
  #Diagonostics: delete later
  print(geo_url)
  print(num_variables)
  print(cat_variables)
  head(pums_tibble)
  head(pums_df)
}
```

Testing exception cases:

```{r, echo=TRUE}
Pums_APIdata(2009)
Pums_APIdata(2012)  
```
